add getDomainFromRequest option, for when domain needs to be calculated
expressjs/session pull request #744
Opened 2020-04-22 21:15 UTC by paulfitz

Thanks for express-session!  Here's a small addition that is perhaps a bit niche but has been useful for us.

This adds a `getDomainFromRequest` option which allows `cookie.domain` to be computed from the request rather than set as a constant.

As an example of when this is useful, imagine serving a single app from `*.foo.com` and `*.bar.com`, with the cookie domain being `.foo.com` for the `*.foo.com` domains and `.bar.com` for the `*.bar.com` domains.

This may be related to https://github.com/expressjs/session/pull/311

2020-04-22 21:19 UTC, dougwilson commented
It seems your scenario is different from that one, and seems achievable though the use of middleware, which is what makes Express so flexible. Have you considered something like
```js
app.use(vhost('*.foo.com', session(fooConfig)))
app.use(vhost('*.bar.com', session(barConfig)))
```

You can pass the same store to both if you want to store sessions in the same place.

2020-04-22 21:57 UTC, paulfitz commented
Thanks for the suggestion! I did consider something similar. In my actual case, the specific domain families are not available to the code, so the middleware needed to do a bit more gymnastics. Overall it felt clumsy, and cleaner to solve in express-session, leaving me with a single session object. However, I can see this is unlikely to be a common case, so it is fine with me if you want to close this out, I won't be offended :-)

2020-04-22 22:00 UTC, dougwilson commented
It's no problem, and I'm not rejecting it to be clear :) I'm more trying to better understand the use-case so we can get to a situation where this is generically solvable and doesn't end up where this needs to be done for every other option, and then someone needs it to be async, etc. etc. :)

There may be a clean way, but I guess I would say it's hard to work together without understanding what you're trying to accomplish. I believed I understood from your initial issue, but it sounds now that what was written there doesn't actually represent your true goals to get from this change.

Is it possible to outline them?

2020-04-22 22:13 UTC, paulfitz commented
I'd now edit:

> As an example of when this is useful, imagine serving a single app from `*.foo.com` and `*.bar.com`, with the cookie domain being `.foo.com` for the `*.foo.com` domains and `.bar.com` for the `*.bar.com` domains.

to be: imagine serving a single app from several domain families (`*.foo.com`, `*.bar.com`, etc.) where the cookie domain should omit the subdomain, and the set of domain families is determined outside of the code (e.g. in dns and load balancer configuration).

Does that make any more sense?  Thanks for your patience.

2020-04-26 20:32 UTC, dougwilson commented
Hi @paulfitz thank you. That does make sense. Sounds like you could use `vhost` to accomplish this (I just wrote it up and didn't extensively test it). The nice thing is that this works with _any_ middleware config, and not even just this module. If this is a pattern that is useful, having a module on npm to wrap around middlewares would be super useful to everyone too.

```js
// example lib that exports a middleware to use for your use-case:
var session = require('express-session')
var vhost = require('vhost')

module.exports = function (options) {
  var cache = Object.create(null)
  return vhost(/^(?:.+\.)?([^.]+\.[^.]+)$/, function (req, res, next) {
    var domain = req.vhost[0]
    var mw = cache[domain]

    if (!mw) {
      var opts = Object.assign({}, options)
      opts.cookie = Object.assign({}, opts.cookie || {})
      opts.cookie.domain = '.' + domain
      cache[domain] = mw = session(opts)
    }

    mw(req, res, next)
  })
}
```

2021-03-20 19:14 UTC, ramiroaisen commented
Upvote for this I have the same trouble here.
I want to share sessions between subdomains,
it would be really nice to have a callback domain config instead of a constant
something like this
```javascript
 session({
  domain: (req: IncommingMessage): string | undefined => req.headers.host // or whatever
})
```
Note that this signature is fully backwards compatible as ```session({domain: "example.com"})``` still works as expected

2022-09-11 11:43 UTC, uriesk commented
Got the same usecase now.
I do not like the vhost or custom middleware solutions because they all create a new session middleware at every single request.
I would prefer callback function that allows to change any cookie settings in an already created session middleware (maybe someone wants to dynamically adjust the expire time?).

2025-03-05 04:39 UTC, dsagal commented
The implementation in this PR is simple, clean, and well-documented, and addresses nicely the use-cases where the domains of the app are dynamic, without affecting behavior when the new option isn't used. Any reason not to merge?

2025-03-07 00:21 UTC, bjohansebas approved these changes
No strong opinions on this functionality, if it helps people then I'm fine with adding it.

2025-04-15 15:38 UTC, Goryounov commented
Hello! I really need this feature, please merge it.

2025-12-18 01:04 UTC, bjohansebas requested changes
I think allowing the configuration to accept a function, as done in https://github.com/expressjs/session/pull/1027, would solve the problem here and we wouldn’t need to add a new option. wdyt?

2026-07-06 03:23 UTC, closed without merging